analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 15
    source-lines-of-code: 50
    maintainability-index: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
    technical-debt: 0

  metrics-exclude:
    - "test/**" # Mengecualikan folder tes
    - "**/*.g.dart" # Mengecualikan file yang di-generate

  folders:
    - lib/app/modules/auth # Fokuskan analisis pada direktori modul Anda

  rules:
    - newline-before-return
    - no-empty-block
    - prefer-trailing-comma
    - no-equal-then-else

  anti-patterns:
    - long-method
    - long-parameter-list